/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation;

/**
 *
 * @author hugo
 */
public class PresentationJFrameMenuConnecter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PresentationJFrameMenuConnecter.class.getName());

    /**
     * Creates new form PresentationJFrameMenu
     */
    public PresentationJFrameMenuConnecter() {
        initComponents();
    }
    
    // 1. Déclarer les modèles (les "cerveaux" de tes listes)
    private javax.swing.DefaultListModel<String> modeleFutur;
    private javax.swing.DefaultListModel<String> modelePasser;

    // 2. Créer une méthode pour lier les modèles et centrer le texte
    public void initFrame() {
        // Initialisation des modèles
        modeleFutur = new javax.swing.DefaultListModel<>();
        modelePasser = new javax.swing.DefaultListModel<>();
        
        // On donne les modèles aux JList créées par NetBeans
        ListeRéservationFutur.setModel(modeleFutur);
        ListeRéservationPasser.setModel(modelePasser);
        
        // Pour centrer le texte dans les listes (comme vu précédemment)
        javax.swing.DefaultListCellRenderer renderer = new javax.swing.DefaultListCellRenderer();
        renderer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListeRéservationFutur.setCellRenderer(renderer);
        ListeRéservationPasser.setCellRenderer(renderer);
        
        // Optionnel : donner un peu d'espace en hauteur aux lignes
        ListeRéservationFutur.setFixedCellHeight(30);
        ListeRéservationPasser.setFixedCellHeight(30);
    }

    // 3. Les méthodes pour REMPLIR les listes
    public void peuplerListeFutur(String[] reservations) {
        modeleFutur.clear(); // On vide au cas où
        for (String resa : reservations) {
            modeleFutur.addElement(resa);
        }
    }

    public void peuplerListePasser(String[] reservations) {
        modelePasser.clear(); // On vide au cas où
        for (String resa : reservations) {
            modelePasser.addElement(resa);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OngletReservation = new javax.swing.JTabbedPane();
        TabReservationFutur = new javax.swing.JPanel();
        PaneReservationFutur = new javax.swing.JScrollPane();
        ListeRéservationFutur = new javax.swing.JList<>();
        TitreReservationFutur = new javax.swing.JLabel();
        ButtonNouvelleRéservation = new javax.swing.JButton();
        TabReservationPasser = new javax.swing.JPanel();
        PaneReservationPasser = new javax.swing.JScrollPane();
        ListeRéservationPasser = new javax.swing.JList<>();
        TitreReservationPasser = new javax.swing.JLabel();
        TabMonCompte = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ListeRéservationFutur.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListeRéservationFutur.setAlignmentX(1.0F);
        PaneReservationFutur.setViewportView(ListeRéservationFutur);

        TitreReservationFutur.setText("Consulter ou annuler vos réservations");

        ButtonNouvelleRéservation.setText("Nouvelle Réservation");
        ButtonNouvelleRéservation.addActionListener(this::ButtonNouvelleRéservationActionPerformed);

        javax.swing.GroupLayout TabReservationFuturLayout = new javax.swing.GroupLayout(TabReservationFutur);
        TabReservationFutur.setLayout(TabReservationFuturLayout);
        TabReservationFuturLayout.setHorizontalGroup(
            TabReservationFuturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabReservationFuturLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(TabReservationFuturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ButtonNouvelleRéservation, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                    .addComponent(TitreReservationFutur)
                    .addComponent(PaneReservationFutur))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        TabReservationFuturLayout.setVerticalGroup(
            TabReservationFuturLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabReservationFuturLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TitreReservationFutur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaneReservationFutur, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonNouvelleRéservation)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        OngletReservation.addTab("Réservations à Venir", TabReservationFutur);

        ListeRéservationPasser.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ListeRéservationPasser.setAlignmentX(1.0F);
        PaneReservationPasser.setViewportView(ListeRéservationPasser);

        TitreReservationPasser.setText("Consulter vos anciennes réservations");

        javax.swing.GroupLayout TabReservationPasserLayout = new javax.swing.GroupLayout(TabReservationPasser);
        TabReservationPasser.setLayout(TabReservationPasserLayout);
        TabReservationPasserLayout.setHorizontalGroup(
            TabReservationPasserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabReservationPasserLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(TabReservationPasserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitreReservationPasser)
                    .addComponent(PaneReservationPasser, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        TabReservationPasserLayout.setVerticalGroup(
            TabReservationPasserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabReservationPasserLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TitreReservationPasser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaneReservationPasser, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        OngletReservation.addTab("Réservations passées", TabReservationPasser);

        javax.swing.GroupLayout TabMonCompteLayout = new javax.swing.GroupLayout(TabMonCompte);
        TabMonCompte.setLayout(TabMonCompteLayout);
        TabMonCompteLayout.setHorizontalGroup(
            TabMonCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );
        TabMonCompteLayout.setVerticalGroup(
            TabMonCompteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 907, Short.MAX_VALUE)
        );

        OngletReservation.addTab("Mon compte", TabMonCompte);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OngletReservation, javax.swing.GroupLayout.PREFERRED_SIZE, 879, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(OngletReservation)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonNouvelleRéservationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNouvelleRéservationActionPerformed
        // TODO add your handling code here:
        System.out.println("presentation.PresentationJFrameMenuConnecter.ButtonNouvelleRéservationActionPerformed()");
    }//GEN-LAST:event_ButtonNouvelleRéservationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PresentationJFrameMenuConnecter().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonNouvelleRéservation;
    private javax.swing.JList<String> ListeRéservationFutur;
    private javax.swing.JList<String> ListeRéservationPasser;
    private javax.swing.JTabbedPane OngletReservation;
    private javax.swing.JScrollPane PaneReservationFutur;
    private javax.swing.JScrollPane PaneReservationPasser;
    private javax.swing.JPanel TabMonCompte;
    private javax.swing.JPanel TabReservationFutur;
    private javax.swing.JPanel TabReservationPasser;
    private javax.swing.JLabel TitreReservationFutur;
    private javax.swing.JLabel TitreReservationPasser;
    // End of variables declaration//GEN-END:variables
}
